language: elixir
otp_release: '20.2'
sudo: required
elixir:
  - '1.5.3'
  - '1.6.3'
before_script:
  sudo redis-server --dir $TRAVIS_BUILD_DIR --dbfilename dump.rdb &
script:
  - mix test
  - mix credo --strict
  - mix dialyzer
